# https://www.netlifycms.org/docs/

backend:
  name: github
  branch: main
  repo: olena195/blog_kyivska_zefirka
locale: uk
media_folder: public/images/uploads
public_folder: "/images/uploads"

collections:
  - name: "pairing"
    label: "пейрінг"
    folder: "content/pairing"
    extension: "json"
    format: "json"
    create: true
    slug: "{{title}}"
    fields:
      - { label: "назва пейрінга", name: "title", widget: "string" }
      - { name: "taxonomy", widget: "hidden", default: true}

  - name: "tags"
    label: "теги"
    folder: "content/tags"
    extension: "json"
    format: "json"
    create: true
    slug: "{{title}}"
    fields:
      - { label: "назва тега", name: "title", widget: "string" }
      - { name: "taxonomy", widget: "hidden", default: true}

  - name: "fandom"
    label: "фандом"
    folder: "content/fandom"
    extension: "json"
    format: "json"
    create: true
    slug: "{{title}}"
    fields:
      - { label: "назва фандома", name: "title", widget: "string" }
      - { name: "taxonomy", widget: "hidden", default: true}

  - name: "arts"
    label: "малюнки"
    folder: "content/arts"
    extension: "json"
    format: "json"
    create: true
    slug: "{{slug}}"
    identifier_field: pairing
    fields:
      - { label: "Фандом", name: "fandom", widget: "relation", collection: "fandom", value_field: "title", search_fields: [ "title" ], multiple: true }
      - { label: "Пейрінг", name: "pairing", widget: "relation", collection: "pairing", value_field: "title", search_fields: [ "title" ], multiple: true }
      - { label: "Теги", name: "tags", widget: "relation", collection: "tags", value_field: "title", search_fields: [ "title" ], multiple: true }
      - { label: "Дата", name: "date",  widget: "date", date_format: true }
      - { label: "Арт", name: "pictures", widget: "image", allow_multiple: false }


  - name: "fanfics"
    label: "фанфіки"
    folder: "content/fanfics"
    create: true
    slug: "{{title}}"
    fields:
      - { label: "Назва", name: "title", widget: "string" }
      - { label: "Фандом", name: "fandom", widget: "relation", collection: "fandom", value_field: "title", search_fields: [ "title" ], multiple: true }
      - { label: "Пейрінг", name: "pairing", widget: "relation", collection: "pairing", value_field: "title", search_fields: [ "title" ], multiple: true }
      - { label: "Розмір", name: "size", widget: "string" }
      - { label: "Теги", name: "tags", widget: "relation", collection: "tags", value_field: "title", search_fields: [ "title" ], multiple: true }
      - { label: "Короткий опис", name: "description", widget: "string" }
      - { label: "Текст", name: "body", widget: "markdown" }

  - name: "comics"
    label: "комікси"
    folder: "content/comics"
    extension: "json"
    format: "json"
    create: true
    slug: "{{slug}}"
    identifier_field: description
    fields:
      - { label: "Фандом", name: "fandom", widget: "relation", collection: "fandom", value_field: "title", search_fields: [ "title" ], multiple: true }
      - { label: "Пейрінг", name: "pairing", widget: "relation", collection: "pairing", value_field: "title", search_fields: [ "title" ], multiple: true }
      - { label: "Теги", name: "tags", widget: "relation", collection: "tags", value_field: "title", search_fields: [ "title" ], multiple: true }
      - { label: "Дата", name: "date",  widget: "date", date_format: true }
      - { label: "Короткий опис", name: "description", widget: "string" }
      - { label: "Комікс", name: "pictures", widget: "list", field: { label: Image, name: image, widget: image } }


  - name: "novels"
    label: "новели"
    folder: "content/novels"
    extension: "json"
    format: "json"
    create: true
    slug: "{{title}}"
    fields:
      - { label: "Назва", name: "title", widget: "string" }
      - { label: "Фандом", name: "fandom", widget: "relation", collection: "fandom", value_field: "title", search_fields: [ "title" ], multiple: true }
      - { label: "Пейрінг", name: "pairing", widget: "relation", collection: "pairing", value_field: "title", search_fields: [ "title" ], multiple: true }
      - { label: "Теги", name: "tags", widget: "relation", collection: "tags", value_field: "title", search_fields: [ "title" ], multiple: true }
      - { label: "Короткий опис", name: "description", widget: "string" }
      - { label: "Новела", name: "novels", widget: "file" }
