backend:
  name: github
  branch: main 
  repo: olena195/blog_kyivska_zefirka
locale: uk
media_folder: public/images/uploads
public_folder: "/images/uploads"

collections:
  - name: "paring" 
    label: "пейрінг" 
    folder: "content/paring" 
    extension: "json"
    format: "json"
    create: true 
    slug: "{{slug}}" 
    fields: 
      - {label: "назва пейрінга", name: "title", widget: "string"}

  - name: "tag" 
    label: "теги" 
    folder: "content/tags" 
    extension: "json"
    format: "json"
    create: true 
    slug: "{{slug}}" 
    fields: 
      - {label: "назва тега", name: "title", widget: "string"}

  - name: "fandom" 
    label: "фандом" 
    folder: "content/fandom" 
    extension: "json"
    format: "json"
    create: true 
    slug: "{{slug}}" 
    fields: 
      - {label: "назва фандома", name: "title", widget: "string"}
      
      
  - name: "arts" 
    label: "малюнки" 
    folder: "content/arts" 
    extension: "json"
    format: "json"
    create: true 
    slug: "{{slug}}" 
    fields: 
      - {label: "Назва", name: "title", widget: "string"}
      - {label: "Фандом", name: "fandom", widget: "relation", collection: "fandom", value_field: "title", search_fields: ["title"], multiple: true}
      - {label: "Пейрінг", name: "paring", widget: "relation", collection: "paring", value_field: "title", search_fields: ["title"], multiple: true}
      - {label: "Теги", name: "tag", widget: "relation", collection: "tag", value_field: "title", search_fields: ["title"], multiple: true}
      - {label: "Короткий опис", name: "description", widget: "string"}
      - {label: "Арт", name: "art", widget: "image", allow_multiple: false}
   
  - name: "fanfics" 
    label: "фанфіки" 
    folder: "content/fanfics" 
    create: true 
    slug: "{{slug}}" 
    fields: 
      - {label: "Назва", name: "title", widget: "string"}
      - {label: "Фандом", name: "fandom", widget: "relation", collection: "fandom", value_field: "title", search_fields: ["title"], multiple: true}
      - {label: "Пейрінг", name: "paring", widget: "relation", collection: "paring", value_field: "title", search_fields: ["title"], multiple: true}
      - {label: "Розмір", name: "size", widget: "string"}
      - {label: "Теги", name: "tag", widget: "relation", collection: "tag", value_field: "title", search_fields: ["title"], multiple: true}
      - {label: "Короткий опис", name: "description", widget: "string"}
      - {label: "Текст", name: "body", widget: "markdown"}

  - name: "comics" 
    label: "комікси" 
    folder: "content/comics" 
    extension: "json"
    format: "json"
    create: true 
    slug: "{{slug}}" 
    fields: 
      - {label: "Назва", name: "title", widget: "string"}
      - {label: "Фандом", name: "fandom", widget: "relation", collection: "fandom", value_field: "title", search_fields: ["title"], multiple: true}
      - {label: "Пейрінг", name: "paring", widget: "relation", collection: "paring", value_field: "title", search_fields: ["title"], multiple: true}
      - {label: "Теги", name: "tag", widget: "relation", collection: "tag", value_field: "title", search_fields: ["title"], multiple: true}
      - {label: "Короткий опис", name: "description", widget: "string"}
      - {label: "Комікс", name: "comics", widget: "list", field: {label: Image, name: image, widget: image}}


  - name: "novels" 
    label: "новели" 
    folder: "content/novels" 
    extension: "json"
    format: "json"
    create: true 
    slug: "{{slug}}" 
    fields: 
      - {label: "Назва", name: "title", widget: "string"}
      - {label: "Фандом", name: "fandom", widget: "relation", collection: "fandom", value_field: "title", search_fields: ["title"], multiple: true}
      - {label: "Пейрінг", name: "paring", widget: "relation", collection: "paring", value_field: "title", search_fields: ["title"], multiple: true}
      - {label: "Теги", name: "tag", widget: "relation", collection: "tag", value_field: "title", search_fields: ["title"], multiple: true}
      - {label: "Короткий опис", name: "description", widget: "string"}
      - {label: "Новела", name: "novels", widget: "file"}